// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwekTAQqJEvSOeH9KJ0-0Sqi4IIujQLWE',
    appId: '1:356570946417:web:a355005f0be44ba01534d0',
    messagingSenderId: '356570946417',
    projectId: 'hacksync-8c13e',
    authDomain: 'hacksync-8c13e.firebaseapp.com',
    storageBucket: 'hacksync-8c13e.firebasestorage.app',
    measurementId: 'G-KB2N0JSQYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP8XE2WsJaRxAhCDMQky-dqMkgX2ztaH4',
    appId: '1:356570946417:android:c2c2aaeaf2be86231534d0',
    messagingSenderId: '356570946417',
    projectId: 'hacksync-8c13e',
    storageBucket: 'hacksync-8c13e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbhTYY2ZCPpEjjUpU6rAEPIrnQgEsWRas',
    appId: '1:356570946417:ios:7fb7040eec63a8781534d0',
    messagingSenderId: '356570946417',
    projectId: 'hacksync-8c13e',
    storageBucket: 'hacksync-8c13e.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbhTYY2ZCPpEjjUpU6rAEPIrnQgEsWRas',
    appId: '1:356570946417:ios:7fb7040eec63a8781534d0',
    messagingSenderId: '356570946417',
    projectId: 'hacksync-8c13e',
    storageBucket: 'hacksync-8c13e.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwekTAQqJEvSOeH9KJ0-0Sqi4IIujQLWE',
    appId: '1:356570946417:web:673c8148a91433ba1534d0',
    messagingSenderId: '356570946417',
    projectId: 'hacksync-8c13e',
    authDomain: 'hacksync-8c13e.firebaseapp.com',
    storageBucket: 'hacksync-8c13e.firebasestorage.app',
    measurementId: 'G-ZQR3JX53L2',
  );
}
